wechatspider/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='wechat/', permanent=False)),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^wechat/', include('wechat.urls')),

    url(r'^api/wechat/', include('wechat.api_urls')),

]

wechatspider/wechat/urls.py
# -*- coding: utf-8 -*-
__author__ = 'yijingping'
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="wechat.index"),
    url(r'^add/$', views.add, name="wechat.add"),
    url(r'^(?P<id_>\d+)/edit/$', views.edit, name="wechat.edit"),
    url(r'^(?P<id_>\d+)/delete/$', views.wechat_delete, name="wechat.wechat_delete"),
    url(r'^(?P<id_>\d+)/topics/$', views.wechat_topics, name="wechat.wechat_topics"),
    url(r'^topic/(?P<id_>\d+)/$', views.topic_detail, name="wechat.topic_detail"),
    url(r'^topic/(?P<id_>\d+)/edit/$', views.topic_edit, name="wechat.topic_edit"),
    url(r'^topic/$', views.topic_list, name="wechat.topic_list"),
    url(r'^topic/available/$', views.topic_available_list, name="wechat.topic_available_list"),

    url(r'^topic/add/$', views.topic_add, name="wechat.topic_add"),
    url(r'^search/$', views.search, name="wechat.search"),


    url(r'^keywords/$', views.keywords_list, name="wechat.keywords_list"),

    url(r'^proxy/(?P<id_>\d+)/edit/$', views.proxy_edit, name="wechat.proxy_edit"),
    url(r'^proxy/status/$', views.proxy_status, name="wechat.proxy_status"),
]

wechatspider/wechat/models.py
# -*- coding: utf-8 -*-
__author__ = 'yijingping'
from django.db import models
from datetime import date, datetime, timedelta

class Wechat(models.Model):
    STATUS_DEFAULT = 0
    STATUS_DISABLE = 1
    STATUS_DELETE = 2
    STATUS_CHOICES = (
        (STATUS_DEFAULT, '默认'),
        (STATUS_DISABLE, '禁用'),
        (STATUS_DELETE, '删除')
    )
    avatar = models.CharField(max_length=500, blank=True, default='', verbose_name='公众号头像')
    qrcode = models.CharField(max_length=500, blank=True, default='', verbose_name='二维码')
    name = models.CharField(max_length=100, verbose_name='公众号')
    wechatid = models.CharField(max_length=100, verbose_name='公众号id', unique=True)
    intro = models.TextField(default='', blank=True, verbose_name='简介')
    frequency = models.IntegerField(default=0, verbose_name='爬取频率, 单位:分钟')
    next_crawl_time = models.DateTimeField(auto_now_add=True, verbose_name='下次爬取时间')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    status = models.IntegerField(default=STATUS_DEFAULT, choices=STATUS_CHOICES, verbose_name="状态")

    def last_day_topics_count(self):
        yestoday = date.today() - timedelta(days=1)
        yestoday_datetime = datetime.combine(yestoday, datetime.min.time())
        return Topic.objects.filter(wechat=self, publish_time__gt=yestoday_datetime).count()

    def last_week_topics_count(self):
        last_week = date.today() - timedelta(days=7)
        last_week_datetime = datetime.combine(last_week, datetime.min.time())
        return Topic.objects.filter(wechat=self, publish_time__gt=last_week_datetime).count()

    def total_topics_count(self):
        return Topic.objects.filter(wechat=self).count()

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = "公众号"


class Topic(models.Model):
    wechat = models.ForeignKey('Wechat', verbose_name='公众号')
    uniqueid = models.CharField(unique=True, max_length=100, verbose_name='url的md5值')
    words = models.IntegerField(default=0, verbose_name='字数')

    url = models.CharField(max_length=500, default='', verbose_name='文章的url')
    url_perm = models.CharField(max_length=500, default='', verbose_name='文章的永久url')
    avatar = models.CharField(max_length=500, default='', verbose_name='缩略图地址')
    title = models.CharField(max_length=200, verbose_name='标题')
    origin_title = models.CharField(max_length=200, default='', verbose_name='原文标题')

    abstract = models.TextField(default='', verbose_name='内容简介')
    content = models.TextField(default='', verbose_name='文章内容')
    source = models.TextField(default='', verbose_name='文章原内容')

    publish_time = models.DateTimeField(db_index=True, verbose_name='发布时间')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='更新时间')
    available = models.CharField(db_index=True, max_length=500, default='', verbose_name='是否可用')

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name_plural = "文章"


class Proxy(models.Model):
    STATUS_NEW = 0
    STATUS_SUCCESS = 1
    STATUS_FAIL = 2
    STATUS_CHOICES = (
        (STATUS_NEW,'未检测'),
        (STATUS_SUCCESS,'检测成功'),
        (STATUS_FAIL,'检测失败'),
    )
    KIND_SEARCH = 0
    KIND_DOWNLOAD = 1
    KIND_CHOICES = (
        (KIND_SEARCH, '搜索代理'),
        (KIND_DOWNLOAD, '下载代理'),
    )
    kind = models.IntegerField(default=KIND_DOWNLOAD, choices=KIND_CHOICES, verbose_name="类型")
    user = models.CharField(default='', blank=True, max_length=100)
    password = models.CharField(default='', blank=True, max_length=100)
    host = models.CharField(max_length=100)
    port = models.IntegerField(default=80)
    speed = models.IntegerField(default=0, verbose_name="连接速度(ms)")
    status = models.IntegerField(default=STATUS_NEW, choices=STATUS_CHOICES, verbose_name="状态")
    retry = models.IntegerField(default=0, verbose_name="尝试次数")
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_time = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        verbose_name_plural = "访问代理"


class Word(models.Model):
    KIND_KEYWORD = 0
    #KIND_TOPIC = 1 #
    KIND_CHOICES = (
        (KIND_KEYWORD, '关键词'),
        #(KIND_TOPIC, '话题'),
    )
    kind = models.IntegerField(default=KIND_KEYWORD, choices=KIND_CHOICES, verbose_name="类型")
    text = models.CharField(max_length=100, verbose_name='词')
    intro = models.TextField(default='', blank=True, verbose_name='简介')
    frequency = models.IntegerField(default=100, verbose_name='爬取频率, 单位:分钟')
    next_crawl_time = models.DateTimeField(auto_now_add=True, verbose_name='下次爬取时间')
    create_time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

    def __unicode__(self):
        return '%s %s' % (self.kind, self.text)

    class Meta:
        verbose_name_plural = "词"

wechatspider/wechat/forms.py
# -*- coding: utf-8 -*-
__author__ = 'yijingping'
from django import forms
from .models import Wechat


class WechatForm(forms.ModelForm):
    class Meta:
        model = Wechat
        fields = ['avatar', 'qrcode', 'name', 'wechatid', 'intro', 'frequency']


class WechatConfigForm(forms.ModelForm):
    class Meta:
        model = Wechat
        fields = ['frequency']

wechatspider/wechat/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
__author__ = 'yijingping'
import json
import requests
from io import StringIO
from lxml import etree
from datetime import datetime
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, JsonResponse
from django.contrib import messages
from django.shortcuts import render_to_response, get_object_or_404, redirect, HttpResponseRedirect
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings
from wechat.constants import KIND_DETAIL
from wechatspider.util import get_redis, login_required
from .forms import WechatForm, WechatConfigForm
from .models import Wechat, Topic, Proxy, Word
from .extractors import download_to_oss

CRAWLER_CONFIG = settings.CRAWLER_CONFIG

import logging
logging.basicConfig()

@login_required
def index(request):
    context = {}
    params = request.GET.copy()
    status = params.get('status', None)
    if status is None:
        _obj_list = Wechat.objects.filter().order_by('-id')
    else:
        _obj_list = Wechat.objects.filter(status=status).order_by('-id')

    paginator = Paginator(_obj_list, 50)  # Show 20 contacts per page

    page = request.GET.get('page')
    try:
        _objs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        _objs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        _objs = paginator.page(paginator.num_pages)

    r = get_redis()
    # 获取代理状态
    proxies = Proxy.objects.filter(kind=Proxy.KIND_DOWNLOAD, status=Proxy.STATUS_SUCCESS)[:1]
    if len(proxies) > 0:
        dt = datetime.now() - proxies[0].update_time
        _proxy_status = '正常' if dt.total_seconds() < 3600 else '异常'
    else:
        _proxy_status = '异常'
    context.update({
        "active_nav": "wechats",
        "wechats": _objs,
        "params": params,
        "downloader": r.llen(CRAWLER_CONFIG['downloader']) or 0,
        "antispider": r.get(CRAWLER_CONFIG['antispider']) or 0,
        "proxy_status": _proxy_status

    })
    print context

    return render_to_response('wechat/index.html', RequestContext(request, context))


def add(request):
    if request.method == 'POST':
        form = WechatForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            if settings.OSS2_ENABLE:
                obj.avatar = download_to_oss(obj.avatar, settings.OSS2_CONFIG["IMAGES_PATH"])
                obj.qrcode = download_to_oss(obj.qrcode, settings.OSS2_CONFIG["IMAGES_PATH"])
            obj.save()
            messages.success(request, '保存成功.')
            return redirect(reverse('wechat.index'))
        else:
            messages.error(request, '添加失败,请重试. 错误: %s' % form.errors)
            return redirect(reverse('wechat.index'))


@login_required
def edit(request, id_):
    wechat = get_object_or_404(Wechat, pk=id_)
    if request.method == 'GET':
        context = {}
        # 编辑信息
        form = WechatConfigForm(instance=wechat)
        context.update({
            "active_nav": "wechats",
            "wechat": wechat,
            "form": form
        })
        return render_to_response('wechat/edit.html', {}, context_instance=RequestContext(request, context))
    elif request.method == 'POST':
        form = WechatConfigForm(request.POST, instance=wechat)
        if form.is_valid():
            obj = form.save(commit=False)
            if obj.frequency > 0:
                obj.next_crawl_time = datetime.now()
            else:
                print obj.status
                if obj.status == Wechat.STATUS_DEFAULT:
                    obj.status = Wechat.STATUS_DISABLE
            obj.save()
            messages.success(request, '保存成功.')
            return redirect(reverse('wechat.edit', kwargs={"id_": id_}))

        else:
            messages.error(request, '保存失败,请重试. 错误: %s' % form.errors)
            return redirect(reverse('wechat.edit', kwargs={"id_": id_}))


@login_required
def wechat_delete(request, id_):
    wechat = get_object_or_404(Wechat, pk=id_)
    wechat.status = Wechat.STATUS_DELETE
    wechat.save()
    next_page = request.GET.get('next')
    return redirect(next_page)


@login_required
def topic_list(request):
    context = {}
    # 文章信息
    params = request.GET.copy()
    _obj_list = Topic.objects.order_by('-publish_time').values('id', 'wechat__id', 'wechat__name', 'wechat__status', 'avatar', 'title', 'url', 'url_perm', 'publish_time', 'available')

    paginator = Paginator(_obj_list, 50 )  # Show 10 contacts per page

    page = request.GET.get('page')
    try:
        _objs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        _objs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        _objs = paginator.page(paginator.num_pages)

    context.update({
        "active_nav": "topics",
        "topics": _objs,
        "params": params
    })
    return render_to_response('wechat/topic_list.html', {}, context_instance=RequestContext(request, context))

@login_required
def topic_available_list(request):
    context = {}
    # 文章信息
    params = request.GET.copy()
    _obj_list = Topic.objects.filter(available='可用').order_by('-publish_time').values('id', 'wechat__id', 'wechat__name', 'avatar', 'title', 'url', 'publish_time', 'available')

    paginator = Paginator(_obj_list, 50 )  # Show 10 contacts per page

    page = request.GET.get('page')
    try:
        _objs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        _objs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        _objs = paginator.page(paginator.num_pages)

    context.update({
        "active_nav": "topics_available",
        "topics": _objs,
        "params": params
    })
    return render_to_response('wechat/topic_available_list.html', {}, context_instance=RequestContext(request, context))


def wechat_topics(request, id_):
    wechat = get_object_or_404(Wechat, pk=id_)
    context = {}
    # 文章信息
    params = request.GET.copy()
    _obj_list = Topic.objects.filter(wechat=wechat).order_by('-publish_time').values('id', 'avatar', 'title', 'url', 'publish_time', 'words')

    paginator = Paginator(_obj_list, 50 )  # Show 10 contacts per page

    page = request.GET.get('page')
    try:
        _objs = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        _objs = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        _objs = paginator.page(paginator.num_pages)

    context.update({
        "active_nav": "wechats",
        "wechat": wechat,
        "topics": _objs,
        "params": params
    })
    return render_to_response('wechat/wechat_topics.html', {}, context_instance=RequestContext(request, context))

@csrf_exempt
@login_required
def topic_detail(request, id_):
    topic = get_object_or_404(Topic, pk=id_)
    return render_to_response('wechat/topic_detail.html', {}, context_instance=RequestContext(request, {
        "topic": topic
    }))

@csrf_exempt
@login_required
def topic_edit(request, id_):
    topic = get_object_or_404(Topic, pk=id_)
    if request.method == 'POST':
        available = request.POST.get('available')
        topic.available = available
        topic.save()
        return JsonResponse({
            'ret': 0,
            'msg': available
        })

@login_required
def topic_add(request):
    url = request.POST.get('url', '')
    if url.startswith('http://mp.weixin.qq.com/') or url.startswith('https://mp.weixin.qq.com/') :
        data = {
            'kind': KIND_DETAIL,
            'url': url
        }

        r = get_redis()
        r.rpush(settings.CRAWLER_CONFIG["downloader"], json.dumps(data))
        messages.success(request, '链接已经提交给爬虫,稍后查看爬取结果.')
    else:
        messages.error(request, 'url 错误, 添加失败')
    return redirect(reverse('wechat.topic_list'))



def search(request):
    query = request.GET.get('query')
    wechats = search_wechat(query)
    return render_to_response('wechat/search_content.html', RequestContext(request, {"wechats": wechats}))


def search_wechat(query):
    p = Proxy.objects.filter(kind=Proxy.KIND_SEARCH, status=Proxy.STATUS_SUCCESS).order_by('?').first()
    if p:
        proxies = {
            'http': 'http://%s:%s' % (p.host, p.port)
        }
    else:
        proxies = {}
    print proxies
    headers = {
            'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36'
    }
    rsp = requests.get("http://weixin.sogou.com/weixin",
                       params={"type": 1, "query": query},
                       proxies=proxies, headers=headers
    )
    rsp.close()
    rsp.encoding = rsp.apparent_encoding
    #print rsp.content
    htmlparser = etree.HTMLParser()
    tree = etree.parse(StringIO(rsp.text), htmlparser)
    nodes = tree.xpath('//div[contains(@class,"wx-rb")]')
    wechats = []
    for node in nodes:
        name =  ''.join([x for x in node.find(".//h3").itertext() if x not in ["red_beg", "red_end"]])
        avatar = node.find('.//img').attrib['src']
        qrcode = node.find(".//div[@class='pos-box']/img").attrib['src']
        wechatid = node.find(".//h4/span/label").text
        intro_node = node.find(".//p/span[2]")
        intro = ''.join([x for x in intro_node.itertext() if x not in ["red_beg", "red_end"]])

        wechats.append({
            "name": name,
            "wechatid": wechatid,
            "avatar": avatar,

wechatspider/wechat/templates/wechat/edit.html
{% extends "base.html" %}

{% block main-content %}
      <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-heading">
                编辑公众号
            </div>
            <div class="panel-body">
              <form id="wechat-edit-form" class="simple_form" action="{% url 'wechat.edit' wechat.id %}" method="post" >

                {% csrf_token %}
                <div class="form-group">
                  <div class="media wechat-item ">
                    <div class="media-left">
                        <img class="media-object avatar-list" src="{{ wechat.avatar }}" alt="{{ wechat.name }}">
                    </div>
                    <div class="media-body">
                      <h5 class="media-heading">{{wechat.name}} <span class="wechat-id">微信号: {{wechat.wechatid}}</span></h5>
                      <p class="intro">
                      {{wechat.intro}}
                      </p>
                    </div>
                    <div class="media-right">
                      <img class="media-object wechat-qrcode" src="{{ wechat.qrcode }}" alt="...">
                    </div>
                  </div>
                  <hr />
                </div>
                <div class="form-group">
                  <div class="input-group">
                    <label for="id_frequency" class="control-label">爬取频率</label>
                    <input id="id_frequency" type="number" class="form-control wechat-frequency" name="frequency" required placeholder="{{ wechat.frequency }}" value="{{ form.frequency.value }}">
                    <span>分钟</span>
                    <button type="submit" class="btn btn-primary" style="margin-left: 20px;">保存</button>
                  </div>
                </div>
              </form>

            </div>
          </div>

        </div>
      </div>
{% endblock %}

wechatspider/wechat/templates/wechat/index.html
{% extends "base.html" %}
{% load paginator %}
{% load staticfiles %}
{% block main-content %}

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-default">
      <div class="panel-heading">
          添加公众号
      </div>
      <div class="panel-body">
        <form id="search-form" class="form-inline simple_form" action="{% url 'wechat.search' %}" >
          <div class="form-group">
              <lable for="id_query">公&nbsp;&nbsp;众&nbsp;&nbsp;号：</lable>
              <input id="id_query" type="text" class="form-control" style="text-align: center;" name="query" required placeholder="逻辑思维 / LJSW888">
          </div>
          <button type="submit" class="btn btn-default">
            <i class="fa fa-search"></i>
          </button>
        </form>
        <div class="form-group" id="search-content" style="margin-top:10px;">

        </div>

        <form id="wechat-add-form" class="form-inline simple_form" action="{% url 'wechat.add' %}" method="post" >
          {% csrf_token %}
          <input type="hidden" name="name" required>
          <input type="hidden" name="wechatid" required>
          <input type="hidden" name="avatar" required>
          <input type="hidden" name="qrcode" required>
          <input type="hidden" name="intro">

          <div class="form-group">
              <lable for="id_frequency">爬取频率：</lable>
              <input id="id_frequency" type="number" class="form-control wechat-frequency" name="frequency" required placeholder="100" value="100">
              <span>&nbsp;分钟</span>
          </div>
          <button type="submit" class="btn btn-primary submit-btn">添加</button>
        </form>

      </div>
    </div>

  </div>
</div>
<div class="row">
  <div class="col-md-12">

    <div class="topics panel panel-default">
      <div class="panel-heading">
          公众号列表
          <span class="pull-right"><a href="{{ params | remove_key:'status' | gen_get_params }}">所有</a> | <a href="{{ params | update_status:0 | gen_get_params }}">活跃</a> | <a href="{{ params | update_status:1 | gen_get_params }}">已禁用</a> | <a href="{{ params | update_status:2 | gen_get_params }}">已删除</a></span>
      </div>
      <div class="panel-body">
        <table class="table table-striped table-hover wechat-table">
          <thead>
            <tr>
              <th>#ID</th>
              <th>头像</th>
              <th>公众号和ID</th>
              <th>爬取频率</th>
              <th>下次爬取时间</th>
              <th>最近1天文章</th>
              <th>最近1周</th>
              <th>文章总数</th>
              <th>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;操作&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</th>
            </tr>
          </thead>
          <tbody>
          {% for item in wechats %}
            <tr class="{% if item.status == 2 %}text-delete{% endif %}{% if item.status == 1 %}text-disable{% endif %}">
              <td><a href="{% url 'wechat.edit' item.id %}">{{ item.id}}</a></td>
              <td><img src="{{ item.avatar | default:'/static/web/images/touxiang.jpg' }}" class="avatar-list"></td>
              <td><h5><a href="{% url 'wechat.wechat_topics' item.id %}">{{ item.name}}</a></h5>
                <span class="wechat-id"><a target="_blank" href="http://weixin.sogou.com/weixin?type=1&query={{ item.wechatid }}&ie=utf8">{{ item.wechatid }}</a></span>
              </td>
              <td>{{ item.frequency}}</td>
              <td>{% if item.frequency > 0 %}{{ item.next_crawl_time}}{% else %}N/A{% endif %}</td>
              <td><a href="{% url 'wechat.wechat_topics' item.id %}">{{ item.last_day_topics_count}}</a></td>
              <td><a href="{% url 'wechat.wechat_topics' item.id %}">{{ item.last_week_topics_count}}</a></td>
              <td><a href="{% url 'wechat.wechat_topics' item.id %}">{{ item.total_topics_count}}</a></td>
              <td>
                <a href="{% url 'wechat.wechat_topics' item.id %}">已爬取文章</a><br/>
                <a target="_blank" href="http://weixin.sogou.com/weixin?type=1&query={{ item.wechatid }}&ie=utf8">源文章列表</a><br/>
                <a href="/admin/wechat/wechat/{{ item.id }}/">编辑</a> |
                <a href="{% url 'wechat.wechat_delete' item.id %}?next={{ request.get_full_path }}">删除</a>
              </td>

            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>

      <div class="panel-footer clearfix">
        {% paginator wechats %}
      </div>

    </div><!--.topics-->

  </div>
</div>
{% endblock %}

{% block footer-js %}
<script src="{% static 'jquery.form.js' %}"></script>
<script src="{% static 'bootstrap-datepicker/js/bootstrap-datepicker.min.js' %}"></script>
<script src="{% static 'bootstrap-datepicker/locales/bootstrap-datepicker.zh-CN.min.js' %}"></script>

<script>
$(document).ready(function() {
    // 微信搜索
    $('#search-form').ajaxForm(function(data) {
        //alert(data);
        $('#search-content').hide().html(data).show('slow');
    });

});
var wechatInfo = {};
function selectWechat(node, name, wechatid, avatar, qrcode, intro){
  // 保存信息
  $("input[name='name']").val(name);
  $("input[name='wechatid']").val(wechatid);
  $("input[name='avatar']").val(avatar);
  $("input[name='qrcode']").val(qrcode);
  $("input[name='intro']").val(intro);
  // 显示选中状态
  $(node).addClass('selected');
  // 隐藏兄弟节点
  $(node).prevAll().hide('slow');
  $(node).nextAll().hide('slow');
}
</script>
{% endblock %}

wechatspider/wechat/templates/wechat/keywords_list.html
{% extends "base.html" %}
{% load paginator %}
{% block main-content %}
<div class="row">
  <div class="col-md-12">
    <div class="topics panel panel-default">
      <div class="panel-heading">
        关键词列表
        <span class="pull-right"><a target="_blank" href="/admin/wechat/word/add/">新增关键词</a></span>
      </div>
      <div class="panel-body">
        <table class="table table-striped table-hover wechat-table">
          <thead>
            <tr>
              <th>#ID</th>
              <th>关键词</th>
              <th>简介</th>
              <th>爬取频率</th>
              <th>下次爬取时间</th>
              <th>操作</th>
            </tr>
          </thead>
          <tbody>
          {% for item in keywords %}
            <tr>
              <td>{{ item.id }}</td>
              <td>{{ item.text }}</td>
              <td>{{ item.intro }}</td>
              <td>{{ item.frequency}}</td>
              <td>{% if item.frequency > 0 %}{{ item.next_crawl_time}}{% else %}N/A{% endif %}</td>
              <td><div><a target="_blank" href="/admin/wechat/word/{{ item.id }}/">编辑</a> | <a target="_blank" href="/admin/wechat/word/{{ item.id }}/delete/">删除</a></div></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
      <div class="panel-footer clearfix">
        {% paginator keywords %}
      </div>
    </div><!--.topics-->

  </div>
</div>
{% endblock %}

wechatspider/wechat/templates/wechat/search_content.html
{% load utils %}
{% for item in wechats %}
<div class="media wechat-item" onclick='selectWechat(this, {{ item.name | escapejs | as_json }}, {{ item.wechatid  | as_json }}, {{ item.avatar | as_json }}, {{ item.qrcode | as_json }}, {{ item.intro | escapejs | as_json }})'>
  <div class="media-left">
      <img class="media-object avatar-list" src="{{ item.avatar }}" alt="...">
  </div>
  <div class="media-body">
    <h5 class="media-heading">{{item.name}} <span class="wechat-id">微信号: {{item.wechatid}}</span></h5>
    <p>
      {{item.intro}}
    </p>
  </div>
  <div class="media-right">
    <img class="media-object wechat-qrcode" src="{{ item.qrcode }}" alt="...">
  </div>
</div>
{% endfor %}

wechatspider/wechat/templates/wechat/topic_detail.html
{% load staticfiles %}
<head>
    <!-- 禁用referrer, 目的是为了显示soso的图片-->
    <meta name="referrer" content="no-referrer" />
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'jquery/jquery-1.11.3.min.js' %}"></script>
</head>

{% load wechat_util %}

<div style="position: fixed; right: 100px; top: 400px; z-index: 200;">
    <div onclick="chooseAvailable({{ topic.id }}, '可用')" style="width: 100px;">
        <label>
            <input class="input-lg" type="checkbox" name="available" id="id_available" {{ topic.available|radio_checked:'可用' }}>
            可用
        </label>
    </div>
</div>
{#{ topic.source | safe }#}

{{ topic.content | safe }}

{% block footer-js %}
    <script>
        var chooseAvailable = function(topic_id, choose_str){
            $.post('/wechat/topic/'+topic_id+'/edit/', {'available': choose_str}, function(data){
                if(data.ret==0){
                    console.log(data.msg);
                }
            });
        }
    </script>
{% endblock %}